services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__Mongo: mongodb://mongo:27017/FeatureFlag

  mongo:
    image: mongo:6.0
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
    driver: local
